[package]
name = "rigglow"
version = "0.1.0"
edition = "2024"
description = "A colorful live Linux hardware fetcher"
license = "MIT"
repository = "https://github.com/tadeycek/RigGlow"
homepage = "https://github.com/tadeycek/RigGlow"
readme = "README.md"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.33"
toml = "0.8"
